notice/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'notice'



urlpatterns = [
    # 因为path第二个参数只接受函数，所以类视图要添加一个as_view()的方法

    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
    path('delete/<int:id>', views.user_delete, name='user_delete'),
    path('edit/<int:id>', views.profile_edit, name='profile_edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='avator/%Y%m%d', blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return '<User: %s>' % self.user.username

userprofile/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .form import UserLoginForm,UserRegisterForm,ProfileForm
from .models import Profile

# Create your views here.


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)
                return redirect('article:article_list')
            else:
                return HttpResponse("账号或密码不正确，请重新输入")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {}
        context['form'] = user_login_form
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


def user_logout(request):
    logout(request)
    return redirect('article:article_list')


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            return redirect('article:article_list')
        else:
            return HttpResponse("注册表单输入有误，请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {}
        context['form'] = user_register_form
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 引用了login_required装饰器，如果没有登录的话则不执行函数，将页面重定向到
@login_required(login_url='userprofile/login')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('article:article_list')
        else:
            return HttpResponse("你没有删除操作的权限")
    else:
        return HttpResponse("仅接受post请求")


@login_required(login_url='userprofile/login')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    # profile = Profile.objects.get(user_id=id)

    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息")

        # 上传的文件保存在request.FILES中，通过参数传递给表单类
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            profile.avatar = profile_cd['avatar']
            profile.save()
            return redirect('userprofile:profile_edit', id=id)
        else:
            return HttpResponse("注册表单输入有误，请重新输入")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {}
        context['profile_form'] = profile_form
        context['user'] = user
        context['profile'] = profile
        return render(request, 'userprofile/edit.html', context)

    else:
        return HttpResponse("请使用GET或POST请求数据")

userprofile/templates/userprofile/edit.html
{% extends 'base.html' %}
{% block title %} 用户信息 {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名：{{ user.username }}</div>
            <br>

            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ MEDIA_URL }}{{ profile.avatar }}" style="max-width: 20%;border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group col-md-4">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" id="avatar" name="avatar">
                </div>


                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>


                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 登录 {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>还没有账号？</h5>
            <h5>点击<a href="{% url 'userprofile:user_register' %}">注册账号</a>加入我们吧！</h5>
            <br>
            <form action="#" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <label for="title">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>

                <div class="form-group">
                    <label for="content">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>

                <button type="submit" class="btn btn-primary">提交</button>

            </form>

            <br>
            <h5>忘记密码？</h5>
            <h5>点击 <a href="{% url 'password_reset_recover' %}">这里</a>重置密码</h5>
        </div>
    </div>
</div>

{% endblock %}

userprofile/templates/userprofile/register.html
{% extends 'base.html' %}
{% block title %} 登录 {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form action="#" method="post">
                {% csrf_token %}
                <div class="form-group clo-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>

                <div class="form-group clo-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>

                <div class="form-group clo-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>

                <div class="form-group clo-md-4">
                    <label for="password2">设置密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>

                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}