article/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'article'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    # path('', views.ArticleListView.as_view(), name='article_list'),
    path('article_detail/<int:id>', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>', views.article_delete, name='article_delete'),
    path('article_safe_delete/<int:id>', views.article_safe_delete, name='article__safe_delete'),
    path('article_update/<int:id>', views.article_update, name='article_update'),
    path('increase_likes/<int:id>', views.IncreaseLikeView.as_view(), name='increase_likes'),
]

comment/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'comment'

urlpatterns = [
    path('post_comment/<int:article_id>/', views.post_comment, name='post_comment'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

notice/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'notice'



urlpatterns = [
    # 因为path第二个参数只接受函数，所以类视图要添加一个as_view()的方法

    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
    path('delete/<int:id>', views.user_delete, name='user_delete'),
    path('edit/<int:id>', views.profile_edit, name='profile_edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from PIL import Image
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class ArticleColumn(models.Model):
    title = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, null=True, blank=True, related_name='article')

    # 使用pillow处理，需要在save()方法中对图片进行处理
    # avatar = models.ImageField(upload_to='article/%Y%m%d', blank=True)

    # 使用更高级的库django-imagekit来处理图片，直接在定义字段就可以给出处理图片的说明
    avatar = ProcessedImageField(
        upload_to='article/%Y%m%d',
        processors=[ResizeToFit(width=400)],
        format='JPEG',
        options={'quality':100},
        blank=True
    )

    # 点赞
    likes = models.PositiveIntegerField(default=0)

    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    # PositiveIntegerField 是用于存储正整数的字段
    total_views = models.PositiveIntegerField(default=0)

    # 应用第三方库django-taggit实现标签功能,这是多对多
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return "<Article: %s>" % self.title

    # def save(self, *args, **kwargs):
    #     # 调用原有的save()方法
    #     article = super(Article, self).save(*args, **kwargs)
    #
    #     # 处理图片
    #     # 第一个判断是过滤没有缩略图的，自然就不用处理；
    #     # 第二个判断是过滤之前做浏览量统计时只更新total_views字段的操作，即save(update_fields=['total_views'])
    #     if self.avatar and not kwargs.get('update_fields'):
    #         image = Image.open(self.avatar)
    #         (x, y) = image.size
    #         new_x = 400
    #         new_y = int(new_x * (y / x))
    #         resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)  # Image.ANTIALIAS表示缩放采用平滑滤波
    #         resized_image.save(self.avatar.path)  # 覆盖掉原始图片
    #
    #     return article


    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    def was_created_centenly(self):
        diff = timezone.now() - self.created_time
        if diff.days ==0 and diff.seconds >= 0 and diff.seconds <= 60:
            return True
        else:
            return False

article/views.py
import markdown
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Q
from django.views.generic import ListView,DetailView
from django.views import View
from .models import Article,ArticleColumn
from .form import ArticleForm
from comment.models import Comment
from comment.form import CommentForm


# 类视图
class ArticleListView(ListView):
    # 上下文的名称
    context_object_name = 'article'
    # 查询集
    queryset = Article.objects.all()
    # 模板位置
    template_name = 'article/list.html'

    # def get_queryset(self):
    #     queryset = Article.objects.filter(title='Python')
    #     return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        # 获取原有的上下文
        context = super().get_context_data(**kwargs)
        # 增加新上下文
        context['order'] = 'total_views'
        return context


class ArticleDetailView(DetailView):
    queryset = Article.objects.all()
    context_object_name = 'article'
    template_name = 'article/detail.html'


# 点赞数 +1
class IncreaseLikeView(View):
    def post(self, request, *args, **kwargs):
        article = Article.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')


# Create your views here.
def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    articles = Article.objects.all()

    if search:

        # 根据GET请求中的查询条件，返回不同的排序对象
        if order == 'total_views':
            # articles = Article.objects.all().order_by('-total_views')
            articles = articles.filter(
                Q(title__icontains=search)  |
                Q(content__icontains=search)  |
                Q()
            ).order_by('-total_views')
        else:
            articles = articles.filter(
                Q(title__icontains=search) |
                Q(content__icontains=search)
            )

    else:
        # 将search置空,因为用户没有搜索，则search=None,相当于模板中查的是“None”的字符串
        search = ''
        if order == 'total_views':
            articles = Article.objects.all().order_by('-total_views')
        else:
            articles = Article.objects.all()

    # isdigit：检测字符串是否只由数字组成
    if column is not None and column.isdigit():
        articles = articles.filter(column=column)

    # tag的过滤
    if tag and tag != 'None':
        # tags__name__in:在tags字段中过滤name为tag的数据条目
        articles = articles.filter(tags__name__in=[tag])


    paginator = Paginator(articles, settings.ARTICLE_OF_PAGE)
    page = request.GET.get('page', 1)
    page_of_articles = paginator.get_page(page)

    context = {}
    context['page_of_articles'] = page_of_articles
    context['order'] = order  # 提供给翻页
    context['search'] = search
    context['column'] = column
    context['tag'] = tag
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = Article.objects.get(id=id)

    # 处理阅读量
    article.total_views += 1
    article.save(update_fields=['total_views'])  # 指定只更新total_views字段，优化执行效率

    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    # 返回页面comment_form，前台也可用ckeditor
    comment_form = CommentForm()

    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展
            'markdown.extensions.toc',
        ])

    article.content = md.convert(article.content)

    context = {}
    context['article'] = article
    context['toc'] = md.toc
    context['comments'] = comments
    context['comment_form'] = comment_form
    return render(request, 'article/detail.html', context)


def article_create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            new_article = article_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)

            # 保存栏目
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST.get('column'))

            new_article.save()

            # Without this next line the tags won't be saved（因为前面用了save(commit=False)，并且models有多对多关系），保存标签
            article_form.save_m2m()

            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_form = ArticleForm()
        context = {}
        context['article_form'] = article_form
        context['columns'] = ArticleColumn.objects.all()
        return render(request, 'article/create.html', context)


def article_delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('article:article_list')


def article_safe_delete(request, id):
    if request.method == 'POST':
        article = Article.objects.get(id=id)
        article.delete()
        return redirect('article:article_list')
    else:
        return HttpResponse("仅允许post请求")


def article_update(request, id):
    article = Article.objects.get(id=id)

    # 前端不可信原则，后端要再次过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章")

    if request.method == "POST":
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article.title = article_form.cleaned_data['title']
            article.content = article_form.cleaned_data['content']

            # 处理栏目
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None

            # 处理标签
            if request.POST['tags'] != 'none':
                # 这个设置方法需要查看api,tags.set()是如何将序列分隔并解包的
                article.tags.set(*request.POST.get('tags').split(','), clear=True)

            # 处理缩略图
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')

            article.save()
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写")
    else:
        article_form = ArticleForm()
        context = {}
        context['article'] = article
        context['article_form'] = article_form
        context['columns'] = ArticleColumn.objects.all()

        # 需要拼接tags，返回给前端页面使用
        context['tags'] = ','.join(x for x in article.tags.names())
        return render(request, 'article/update.html', context)

article/templates/article/create.html
{% extends 'base.html' %}

{% block title %} 写文章 {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="#" method="post">
                {% csrf_token %}

                <!-- 缩略图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" id="avatar" name="avatar">
                </div>

                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>

                <!-- 栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select name="column" id="column" class="form-control">
                        <option value="none">请选择栏目...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}

                    </select>
                </div>

                <!-- 标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags">
                </div>

                <div class="form-group">
                    <label for="content">文章正文</label>
                    <textarea type="text" class="form-control" id="content" name="content" rows="12"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">完成</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}

article/templates/article/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load mptt_tags %}

{% block title %}
    文章详情
{% endblock %}

{% block content %}

<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    作者：{{ article.author }}
                    {#  <a href="#" onclick="confirm_delete()">删除文章</a>#}

                    {% if article.author == user %}
                        <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                        <a href="{% url 'article:article_update' article.id %}">编辑文章</a>

                    {% endif %}

                    <!-- 新增一个隐藏的表单 -->
                    <form
                            action="{% url 'article:article_delete' article.id %}"
                            id="safe_delete"
                            method="post"
                            style="display: none"
                    >
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>

                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>

            <div class="col-12">
                <p>{{ article.content | safe }}</p>
            </div>

            <!-- 点赞 -->
            <div class="mt-4" style="text-align: center;">
                <button class="btn btn-outline-danger" type="button"
                        onclick="validate_is_like('{% url 'article:increase_likes' article.id %}', {{ article.id }}, {{ article.likes }})">
                    <span>点赞</span>
                    <span>
                        <i class="fas fa-heart"></i>
                    </span>
                    <span id="likes_number">
                        {{ article.likes }}
                    </span>
                </button>
            </div>



            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form action="{% url 'comment:post_comment' article.id %}" method="post">
                        {% csrf_token %}
                        <div class="from-group">
                            <label for="content">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>

{#                            <textarea name="content" id="content" rows="2" type="text" class="form-control"></textarea>#}

                            <div>
                                {{ comment_form.media }}  {# 编辑器自身的渲染代码 #}
                                {{ comment_form.content }}
                            </div>
                        </div>

                        <button style="margin-top: 1em" type="submit" class="btn btn-primary">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:user_login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}


            <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
{#                {% for comment in comments %}#}
{#                    <hr>#}
{#                    <p>#}
{#                        <strong style="color:pink">#}
{#                            {{ comment.user }}#}
{#                        </strong> 于#}
{#                        <span style="color: green">#}
{#                            {{ comment.created_time | date:"Y-m-d h:i:s" }}#}
{#                        </span> 时说:#}
{#                    </p>#}
{#                    <pre style="font-family: inherit; font-size: 1em">{{ comment.content|safe }}</pre>#}
{#                {% endfor %}#}

                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    <!-- 给node取个别名 comment -->
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                             id="comment_elem_{{ comment.id }}"
                        >

                            <hr>
                            <p>
                                <strong style="color:pink;">
                                    {{ comment.user }}
                                </strong>

                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right" style="color: cornflowerblue"></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}
                            </p>
                            <div>{{ comment.content | safe }}</div>

                            <div>
                                <span style="color:gray">
                                    {{ comment.created_time | date:"Y-m-d H:i" }}
                                </span>

                                <!-- 模态框 -->
                                {% if user.is_authenticated %}
                                    <button type="button" class="btn btn-light btn-sm text-muted" onclick="load_modal({{ article.id }},{{ comment.id }})">
                                        回复
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted" href="{% url 'userprofile:user_login' %}">
                                        登录后
                                    </a>回复
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="comment_{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="CommentModalCenter" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}:</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>

                    {% endwith %}
                {% endrecursetree %}
            </div>
        </div>

        <!-- 目录 -->
        <div id="sidebar" class="siderbar">
            <div class="siderbar__inner">
                <h4 style="margin-top: 1em"><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc | safe }}
                </div>
            </div>
        </div>

    </div>
</div>

<style>
.sidebar{
    will-change: min-height;
}

.sidebar__inner{
    transform: translate(0, 0);
    transform: translate3d(0, 0, 0);
    will-change: position, transform;
}
</style>

{% endblock content%}

{% block script %}
    <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'csrf.js' %}"></script>
    <script type="text/javascript">
        // 设置粘性侧边栏
        $('#sidebar').stickySidebar({
            topSpacing: 20,
            bottomSpacing: 20,
        });

        // 设置ckeditor自适应
        $(".django-ckeditor-widget").removeAttr('style');

        {# 这种方式不能防止csrf攻击 #}
        function confirm_delete() {
            layer.open({
                title:"确认删除",
                content:"确认删除这篇文章吗?",
                yes:function (index, layero) {
                    location.href='{% url "article:article_delete" article.id %}'
                },
            })
        }

        function confirm_safe_delete() {
            layer.open({
                title:"确认删除",
                content:"确认删除这篇文章吗?",
                yes:function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                },
            })
        }


        // 加载 modal
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length ===0){
                let content = '<iframe src="/comment/post_comment/' +
                               article_id +
                              '/' +
                               comment_id +
                              '"' +
                              ' frameborder="0" style="width:100%; height:90%;" id="iframe_' +
                               comment_id +
                              '"></iframe>';

                $(modal_body).append(content);
            }

            $(modal_id).modal('show');
        }

        // 二级跳转锚点的方法，但是不可用
        function post_reply_and_show_it(new_comment_id) {
            console.log("这是父页面"+new_comment_id)
            let next_url = '{% url 'article:article_detail' article.id %}';

            // 处理next_url，因为可能最后一个字符是/，但是我们要加锚点的话，不需要/
            // charAt从0~length-1
            next_url = next_url.charAt(next_url.length-1) === '/' ? next_url.slice(0, -1) : next_url;

            next_url = "http://127.0.0.1:8000" + next_url + "#comment_elem_" + new_comment_id;

            console.log(next_url);
            window.location.href= next_url
        }


        // 点赞功能主函数
        function validate_is_like(url, article_id, likes) {
            // 取出 LocalStorage 中的数据
            let storage = window.localStorage;
            const storage_str_data = storage.getItem("my_blog_data");  //const定义的变量不可以修改，而且必须初始化
            let storage_json_data = JSON.parse(storage_str_data);

            // 若数据不存在，则创建空字典
            if (! storage_json_data) {
                storage_json_data = {};
            }

            // 检查当前文章是否已点赞，是则status=true
            const status = check_status(storage_json_data, article_id);

            if (status){
                layer.msg("已经点过赞了哟~");

                // 点过赞，那就直接退出函数
                return ;
            } else{
                // 用 Jquery 找到点赞数量，并 +1
                $("#likes_number").text(likes + 1).css('color', '#dc3545');
            }

            // 用ajax向后端发送post请求
            $.post(
                url,
                {},
                function (result) {
                    if (result === 'success') {
                        // 修改数据
                        try {
                            storage_json_data[article_id] = true;
                        }catch (e) {
                            window.LocalStorage.clear();
                        }

                        // 将字典转换为字符串，以便存储到LocalStorage
                        const d = JSON.stringify(storage_json_data);
                        // 存储点赞数据到 LocalStorage
                        try {
                            storage.setItem("my_blog_data", d);
                        }catch (e) {
                            // code 22错误 表示LocalStorage 空间满了
                            if (e.code === 22){
                                window.LocalStorage.clear();
                                storage.setItem("my_blog_data", d);
                            }
                        }
                    }else {
                        layer.msg("与服务器通信失败...过一会再试试哈~")
                    }
                }
            )
        }


        // 点赞功能辅函数
        function check_status(data, article_id) {
            // 尝试查询点赞状态
            try {
                if(article_id in data && data[article_id]){
                    return true;
                }else {
                    return false;
                }

            } catch (e) {
                window.LocalStorage.clear();
                return false;
            }

        }

    </script>


{% endblock %}

article/templates/article/update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} 更新文章 {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <!-- 栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control" name="column" id="column">
                        <option value="none">请选择栏目...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- 标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags" value="{{ tags }}">
                </div>

                <div class="form-group">
                    <label for="content">文章正文</label>
                    <textarea type="text" class="form-control" id="content" name="content" rows="12">{{ article.content }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">完成</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}