article/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'article'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    # path('', views.ArticleListView.as_view(), name='article_list'),
    path('article_detail/<int:id>', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>', views.article_delete, name='article_delete'),
    path('article_safe_delete/<int:id>', views.article_safe_delete, name='article__safe_delete'),
    path('article_update/<int:id>', views.article_update, name='article_update'),
    path('increase_likes/<int:id>', views.IncreaseLikeView.as_view(), name='increase_likes'),
]

notice/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'notice'



urlpatterns = [
    # 因为path第二个参数只接受函数，所以类视图要添加一个as_view()的方法

    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

# Django2.0之后，app的urls.py必须配置app_name，否则会报错
app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
    path('delete/<int:id>', views.user_delete, name='user_delete'),
    path('edit/<int:id>', views.profile_edit, name='profile_edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100"></button>

<script>
    $(function () {
        $("#BackTop").click(function () {
            $('html,body').animate({scrollTop:0}, 500);
        });

        $(window).scroll(function () {
            if ($(this).scrollTop() >300) {
                $('#BackTop').fadeIn(300);
            }else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!-- 网站主语言 -->
<html lang="zh-cn"></html>

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">

    <!-- 预留网站标题位置 -->
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- 引入代码高亮的css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <!-- 引入在线的矢量图标 -->
    <link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    >

</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}

    <div id="wrapper">
        <!-- 预留具体的页面位置 -->
        {% block content %}{% endblock %}

        <div id="push"></div>
    </div>

    <!-- 引入注脚 -->
    {% include 'footer.html' %}

    <script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.js' %}"></script>

    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>

    <!-- 修改pyments的表格默认的表格样式 -->
    <script>
        $('div#article_body table').addClass('table table-bordered');
        $('div#article_body thead').addClass('thead-light');
    </script>

    <script type="text/javascript" src="{% static 'popper/poper-1.15.0.js' %}"></script>

    <!-- 因为bootstrap.js依赖jquery.js和popper.js，所以它们要先引入 -->
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    {% include 'back_to_top_func.html' %}

    {% block script %}{% endblock %}

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>

templates/footer.html
{% load staticfiles %}

<div>
    <br><br><br>
</div>

<!-- 移除掉了 fixed-bottom 因为会覆盖掉浮动按钮 -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.huanleichen.com 2019</p>
    </div>
</footer>

templates/header.html
<!-- 加载notification模板标签 -->
{% load notifications_tags %}
{% notifications_unread as unread_count %}


<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>#}
{#                </li>#}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8" width="8px" height="8px">
                                    <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                                </svg>
                            {% endif %}
                            
                            {{ user.username }}
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">写文章</a>
                            <a class="dropdown-item" href="{% url 'userprofile:profile_edit' user.id %}">个人信息</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url 'userprofile:user_logout' %}">退出登录</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">登录</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<!-- 新增一个隐藏的表单 -->
    <form
            action="{% url 'userprofile:user_delete' user.id %}"
            id="user_delete"
            method="post"
            style="display: none"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    
    
    <script>
        function user_delete() {
            layer.open({
                title:"确认删除",
                content:"确认删除用户资料吗？",
                yes:function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index)
                }
            })
        }
    </script>
{% endif %}